site_name: Volgin Leonid K33391 labs
nav:
  - Лабораторная 1:
    - 1: task_1.md
    - 2: task_2.md
    - 3: task_3.md
    - 4: task_4.md
    - 5: task_5.md
  - Лабораторная 2: lab_2.md
  - Лабораторная 3: lab_3.md
  - Лабораторная 4: lab_4.md
  - Практика 3:
    - Практика 1: Practice_3_1.md
    - Практика 2: Practice_3_2.md