site_name: Volgin Leonid K33391 1 lab
nav:
  - Лабораторная 1.1: task_1.md
  - Лабораторная 1.2: task_2.md
  - Лабораторная 1.3: task_3.md
  - Лабораторная 1.4: task_4.md
  - Лабораторная 1.5: task_5.md
  - Лабораторная 2: lab_2.md
  - Лабораторная 3: lab_3.md